#!/usr/bin/env python3
"""
export_weights.py
best_1dcnn.pth → model_weights.h (C float 배열)

BatchNorm을 Conv에 융합(fuse)하여 C에서 BN 연산 불필요
실행: python3 export_weights.py
"""

import sys
from pathlib import Path
import numpy as np
import torch

ROOT = Path(__file__).resolve().parent.parent
PTH  = ROOT / "results" / "best_1dcnn.pth"
OUT  = Path(__file__).resolve().parent / "model_weights.h"


def fuse_bn(conv_w, conv_b, bn_gamma, bn_beta, bn_mean, bn_var, eps=1e-5):
    """Conv + BatchNorm 융합 → (fused_weight, fused_bias)"""
    scale = bn_gamma / np.sqrt(bn_var + eps)            # (out_ch,)
    fw = conv_w * scale[:, None, None]                  # (out_ch, in_ch, k)
    fb = (conv_b - bn_mean) * scale + bn_beta           # (out_ch,)
    return fw, fb


def arr2c(name, arr, indent=0):
    """numpy array → C float[] 선언 문자열"""
    flat = arr.flatten().tolist()
    sp   = " " * indent
    vals = ", ".join(f"{v:.8e}f" for v in flat)
    return f"static const float {name}[{len(flat)}] = {{\n{sp}  {vals}\n{sp}}};\n"


def main():
    if not PTH.exists():
        print(f"오류: {PTH} 없음 — 먼저 train_1dcnn.ipynb 실행 필요")
        sys.exit(1)

    ck = torch.load(PTH, map_location="cpu", weights_only=False)
    sd = ck["model_state"]
    hp = ck.get("hyperparams", {})
    n_filters = hp.get("n_filters", 16)

    def t(key):
        return sd[key].numpy()

    # ── Conv+BN 융합 ──────────────────────────────────────────────
    layers = [
        ("CONV1", "encoder.0", "encoder.1"),
        ("CONV2", "encoder.3", "encoder.4"),
        ("CONV3", "encoder.6", "encoder.7"),
        ("CONV4", "encoder.9", "encoder.10"),
    ]

    fused = {}
    for tag, c, b in layers:
        fw, fb = fuse_bn(
            t(f"{c}.weight"), t(f"{c}.bias"),
            t(f"{b}.weight"), t(f"{b}.bias"),
            t(f"{b}.running_mean"), t(f"{b}.running_var"),
        )
        fused[f"W_{tag}"] = fw
        fused[f"B_{tag}"] = fb

    fused["W_FC1"] = t("head.1.weight")
    fused["B_FC1"] = t("head.1.bias")
    fused["W_FC2"] = t("head.4.weight")
    fused["B_FC2"] = t("head.4.bias")

    # ── 출력 치수 계산 ────────────────────────────────────────────
    def conv_out(l, k, s, p):
        return (l + 2*p - k) // s + 1

    in_len = 1250
    L = [in_len]
    params = [(15,2,7),(7,2,3),(5,2,2),(5,2,2)]
    for k,s,p in params:
        L.append(conv_out(L[-1], k, s, p))
    L1, L2, L3, L4 = L[1], L[2], L[3], L[4]

    # ── C 헤더 생성 ───────────────────────────────────────────────
    lines = [
        "/* model_weights.h — auto-generated by export_weights.py */",
        "/* DO NOT EDIT MANUALLY */",
        "#ifndef MODEL_WEIGHTS_H",
        "#define MODEL_WEIGHTS_H",
        "",
        f"#define N_FILTERS  {n_filters}",
        f"#define F1  {n_filters}",
        f"#define F2  {n_filters*2}",
        f"#define F4  {n_filters*4}",
        f"#define TRIM_START 1200",
        f"#define TRIM_COUNT {in_len}",
        f"#define L1_OUT {L1}",
        f"#define L2_OUT {L2}",
        f"#define L3_OUT {L3}",
        f"#define L4_OUT {L4}",
        "",
    ]

    for name, arr in fused.items():
        lines.append(arr2c(name, arr))

    lines += ["#endif /* MODEL_WEIGHTS_H */", ""]

    OUT.write_text("\n".join(lines))
    print(f"생성 완료: {OUT}")
    total = sum(v.size for v in fused.values())
    print(f"가중치 총합: {total:,} floats ({total*4/1024:.1f} KB)")
    for k,v in fused.items():
        print(f"  {k:<10s} {v.shape}")


if __name__ == "__main__":
    main()
