#!/usr/bin/env python3
"""
export_tflite.py
PyTorch best_1dcnn.pth → ONNX → TFLite INT8

출력:
  model_int8.tflite   — MCU Flash에 올릴 양자화 모델
  model_int8.h        — C 바이트 배열 (xxd 변환)

실행:
  python3 export_tflite.py
"""

import sys, json, re, subprocess
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

ROOT      = Path(__file__).resolve().parent.parent
PTH       = ROOT / "results" / "best_1dcnn.pth"
USDATA    = ROOT / "usdata" / "data"
OUT_DIR   = Path(__file__).resolve().parent
ONNX_PATH = OUT_DIR / "model.onnx"
TFLITE_DIR= OUT_DIR / "tflite_out"
TFLITE_INT8 = OUT_DIR / "model_int8.tflite"
HEADER_OUT  = OUT_DIR / "model_int8.h"

TRIM_START, TRIM_COUNT = 1200, 1250
FILENAME_RE = re.compile(
    r'^(?P<name>.+)_(?P<date>\d{8})_(?P<time>\d{6})_'
    r'\((?P<pos_num>\d+)\)(?P<position>.+?)_(?P<gender>[MF])\.csv$'
)


# ── 모델 정의 (train_1dcnn.ipynb 와 동일) ────────────────────────────────────
class SkinCNN(nn.Module):
    def __init__(self, n_filters=16, dropout=0.3):
        super().__init__()
        f = n_filters
        self.encoder = nn.Sequential(
            nn.Conv1d(1,   f,   kernel_size=15, stride=2, padding=7),  nn.BatchNorm1d(f),   nn.ReLU(),
            nn.Conv1d(f,   f*2, kernel_size=7,  stride=2, padding=3),  nn.BatchNorm1d(f*2), nn.ReLU(),
            nn.Conv1d(f*2, f*4, kernel_size=5,  stride=2, padding=2),  nn.BatchNorm1d(f*4), nn.ReLU(),
            nn.Conv1d(f*4, f*4, kernel_size=5,  stride=2, padding=2),  nn.BatchNorm1d(f*4), nn.ReLU(),
            nn.AdaptiveAvgPool1d(1),
        )
        self.head = nn.Sequential(
            nn.Flatten(),
            nn.Linear(f*4, f*2), nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(f*2, 2),
        )
    def forward(self, x):
        return self.head(self.encoder(x))


# ── 대표 데이터셋 (INT8 교정용) ────────────────────────────────────────────
def load_adc(path):
    adc = []
    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line: continue
            try:
                v = int(line)
                if 0 <= v <= 255: adc.append(v)
            except ValueError:
                pass
    adc = np.array(adc, dtype=np.float32)
    if len(adc) > TRIM_COUNT:
        end = TRIM_START + TRIM_COUNT
        adc = adc[TRIM_START:end] if len(adc) >= end else adc[TRIM_START:]
    if len(adc) < TRIM_COUNT:
        adc = np.pad(adc, (0, TRIM_COUNT - len(adc)))
    return adc[:TRIM_COUNT]


def collect_calibration_samples(n=100):
    samples = []
    for csv_path in sorted(USDATA.rglob("*.csv")):
        if "_positions" in csv_path.name: continue
        if not FILENAME_RE.match(csv_path.name): continue
        adc = load_adc(csv_path)
        x = (adc - 128.0) / 128.0
        samples.append(x.reshape(1, 1, TRIM_COUNT).astype(np.float32))
        if len(samples) >= n: break
    print(f"교정 샘플: {len(samples)}개")
    return samples


# ── 1단계: PyTorch → ONNX ────────────────────────────────────────────────────
def export_onnx(model):
    model.eval()
    dummy = torch.zeros(1, 1, TRIM_COUNT)
    torch.onnx.export(
        model, dummy, str(ONNX_PATH),
        input_names=["adc_signal"],
        output_names=["thickness"],
        dynamic_axes={"adc_signal": {0: "batch"}},
        opset_version=17,
    )
    print(f"ONNX 저장: {ONNX_PATH}")


# ── 2단계: ONNX → TFLite INT8 (onnx2tf + 대표 데이터셋 양자화) ──────────────
def export_tflite(calib_samples):
    import onnx2tf

    TFLITE_DIR.mkdir(exist_ok=True)

    # 대표 데이터셋: onnx2tf가 기대하는 형식 {입력명: ndarray (N, *shape)}
    rep_data = {"adc_signal": np.concatenate(calib_samples, axis=0)}  # (N,1,1250)
    print(f"  대표 데이터셋: {rep_data['adc_signal'].shape}")

    onnx2tf.convert(
        input_onnx_file_path=str(ONNX_PATH),
        output_folder_path=str(TFLITE_DIR),
        output_integer_quantized_tflite=True,   # INT8 양자화
        quant_type="per_channel",               # 채널별 양자화 (정확도 우선)
        input_output_quant_dtype="int8",        # 입출력도 INT8
        representative_dataset=rep_data,
        non_verbose=True,
    )

    # INT8 tflite 파일 탐색 (_integer_quant 접미사)
    int8_candidates = sorted(TFLITE_DIR.glob("*integer_quant*.tflite"))
    if not int8_candidates:
        # fallback: 어떤 tflite든
        int8_candidates = sorted(TFLITE_DIR.glob("*.tflite"))

    if not int8_candidates:
        print("경고: TFLite 파일을 찾지 못했습니다. tflite_out/ 디렉토리를 확인하세요.")
        sys.exit(1)

    import shutil
    src = int8_candidates[0]
    shutil.copy(src, TFLITE_INT8)
    print(f"  TFLite 저장: {src.name} → model_int8.tflite")


# ── 3단계: TFLite → C 헤더 ────────────────────────────────────────────────────
def tflite_to_c_header():
    data = TFLITE_INT8.read_bytes()
    size = len(data)

    lines = [
        "/* model_int8.h — auto-generated by export_tflite.py */",
        "/* DO NOT EDIT MANUALLY */",
        "#ifndef MODEL_INT8_H",
        "#define MODEL_INT8_H",
        "",
        f"#define MODEL_INT8_SIZE {size}",
        "",
        f"static const unsigned char model_int8_data[{size}] = {{",
    ]
    hex_vals = ", ".join(f"0x{b:02x}" for b in data)
    # 16바이트마다 줄바꿈
    chunks = [hex_vals[i:i+16*6] for i in range(0, len(hex_vals), 16*6)]
    for chunk in chunks:
        lines.append(f"  {chunk}")
    lines += ["};", "", "#endif /* MODEL_INT8_H */", ""]

    HEADER_OUT.write_text("\n".join(lines))
    print(f"C 헤더 저장: {HEADER_OUT}  ({size} bytes, {size/1024:.1f} KB)")


# ── 4단계: PyTorch vs TFLite 정확도 비교 ──────────────────────────────────────
def validate(model, calib_samples):
    print("\n[검증] PyTorch vs TFLite (첫 5샘플)")
    print(f"{'#':>3}  {'PT-D':>8}  {'PT-F':>8}  {'TF-D':>8}  {'TF-F':>8}  {'ΔD':>7}  {'ΔF':>7}")
    print("-" * 60)

    try:
        from onnxruntime import InferenceSession
        sess = InferenceSession(str(TFLITE_INT8))  # ONNX Runtime으로 TFLite 실행 불가
    except Exception:
        pass

    # onnxruntime으로 ONNX 모델 검증
    try:
        from onnxruntime import InferenceSession
        sess = InferenceSession(str(ONNX_PATH))

        model.eval()
        with torch.no_grad():
            for i, x in enumerate(calib_samples[:5]):
                pt_out = model(torch.tensor(x)).numpy()[0]
                tf_out = sess.run(None, {"adc_signal": x})[0][0]
                print(f"{i+1:>3}  {pt_out[0]:>8.3f}  {pt_out[1]:>8.3f}"
                      f"  {tf_out[0]:>8.3f}  {tf_out[1]:>8.3f}"
                      f"  {abs(pt_out[0]-tf_out[0]):>7.4f}  {abs(pt_out[1]-tf_out[1]):>7.4f}")
    except Exception as e:
        print(f"  검증 건너뜀: {e}")


# ── 메인 ──────────────────────────────────────────────────────────────────────
def main():
    if not PTH.exists():
        print(f"오류: {PTH} 없음"); sys.exit(1)

    ck    = torch.load(PTH, map_location="cpu", weights_only=False)
    hp    = ck.get("hyperparams", {})
    model = SkinCNN(n_filters=hp.get("n_filters", 16),
                    dropout=hp.get("dropout", 0.3))
    model.load_state_dict(ck["model_state"])
    model.eval()
    print(f"모델 로드: n_filters={hp.get('n_filters',16)}")

    calib = collect_calibration_samples(100)

    print("\n[1/3] PyTorch → ONNX")
    export_onnx(model)

    print("\n[2/3] ONNX → TFLite INT8")
    export_tflite(calib)

    print("\n[3/3] TFLite → C 헤더")
    tflite_to_c_header()

    validate(model, calib)

    tflite_size = TFLITE_INT8.stat().st_size
    print(f"\n완료:")
    print(f"  model_int8.tflite : {tflite_size:,} bytes ({tflite_size/1024:.1f} KB)")
    print(f"  model_int8.h      : {HEADER_OUT.stat().st_size/1024:.1f} KB")
    print(f"  Flash 절감 (vs float32 C) : {144 - tflite_size/1024:.0f} KB 절감 예상")


if __name__ == "__main__":
    main()
